namespace CititorRSS.Jaws;

/// <summary>Construiește setările sigure pentru un backup, fără cheile API.</summary>
public static class BackupPolicy
{
    public static AppSettings SanitizeSettings(AppSettings settings) => new()
    {
        UiLanguage = settings.UiLanguage,
        Shortcuts = new Dictionary<string, string>(settings.Shortcuts),
        ArticleRules = (settings.ArticleRules ?? []).Select(rule => rule.Copy()).ToList(),
        ColorScheme = settings.ColorScheme,
        AutoCleanupEnabled = settings.AutoCleanupEnabled,
        RetentionDays = settings.RetentionDays,
        UpdateAtStartup = settings.UpdateAtStartup,
        CheckAppUpdatesAtStartup = settings.CheckAppUpdatesAtStartup,
        ArticleExportFolder = settings.ArticleExportFolder,
        ArticleExportFormat = settings.ArticleExportFormat,
        SoundAlertsEnabled = settings.SoundAlertsEnabled,
        SoundAlertOnSuccess = settings.SoundAlertOnSuccess,
        SoundAlertOnNewArticles = settings.SoundAlertOnNewArticles,
        SoundAlertOnErrors = settings.SoundAlertOnErrors,
        AiInstructions = settings.AiInstructions,
        AiDefaultProvider = AiProviderIds.Normalize(settings.AiDefaultProvider),
        GeminiEnabled = false,
        EncryptedGeminiKey = null,
        OpenAiEnabled = false,
        EncryptedOpenAiKey = null,
        OpenAiModel = settings.OpenAiModel,
        MistralEnabled = false,
        EncryptedMistralKey = null,
        MistralModel = settings.MistralModel,
        DeepSeekEnabled = false,
        EncryptedDeepSeekKey = null,
        DeepSeekModel = settings.DeepSeekModel,
        DeepLEnabled = false,
        EncryptedDeepLKey = null,
        GoogleTranslateSourceLanguage = settings.GoogleTranslateSourceLanguage,
        GoogleTranslateTargetLanguage = settings.GoogleTranslateTargetLanguage,
        NewsBlurConnected = false,
        NewsBlurUsername = null,
        EncryptedNewsBlurSession = null,
        NewsBlurBootstrapCompletedUsername = null,
        NewsBlurSavedStoryMode = settings.NewsBlurSavedStoryMode,
        NewsBlurSyncFeedsAndFoldersAtStartup = settings.NewsBlurSyncFeedsAndFoldersAtStartup,
        NewsBlurSyncArticlesAndStatesAtStartup = settings.NewsBlurSyncArticlesAndStatesAtStartup,
        NewsBlurAutoSyncEnabled = settings.NewsBlurAutoSyncEnabled,
        NewsBlurAutoSyncMinutes = settings.NewsBlurAutoSyncMinutes,
        NewsBlurPendingFeedDeletions = (settings.NewsBlurPendingFeedDeletions ?? []).Where(item => item is not null).Select(item => new NewsBlurPendingFeedDeletion
        {
            FeedId = item.FeedId,
            Url = item.Url,
            Name = item.Name,
            Folder = item.Folder,
            QueuedAt = item.QueuedAt
        }).ToList(),
        LastFolder = settings.LastFolder,
        LastFeedId = settings.LastFeedId,
        LastArticleId = settings.LastArticleId,
        LastArticleLink = settings.LastArticleLink,
        LastArticleFilter = settings.LastArticleFilter,
        LastTimeFilter = settings.LastTimeFilter,
        LastTagFilter = settings.LastTagFilter,
        LastView = settings.LastView,
        LastPanel = settings.LastPanel,
        LastAttentionFilter = settings.LastAttentionFilter,
        HideRepeatedArticlesInGlobalViews = settings.HideRepeatedArticlesInGlobalViews,
        ReadNowFavoriteDays = settings.ReadNowFavoriteDays,
        SpeechEngine = settings.SpeechEngine,
        SpeechVoiceName = settings.SpeechVoiceName,
        EspeakVoiceName = settings.EspeakVoiceName,
        EspeakVariant = settings.EspeakVariant,
        GeminiVoiceName = settings.GeminiVoiceName,
        EspeakPitch = settings.EspeakPitch,
        EspeakInflection = settings.EspeakInflection,
        SpeechRate = settings.SpeechRate,
        SpeechVolume = settings.SpeechVolume,
        StopSpeechWhenLeavingArticle = settings.StopSpeechWhenLeavingArticle,
        ReaderMode = ReaderModeIds.Normalize(settings.ReaderMode),
        ArticleOpenMode = ArticleOpenModeIds.Normalize(settings.ArticleOpenMode),
        ReaderWindowWidth = settings.ReaderWindowWidth,
        ReaderWindowHeight = settings.ReaderWindowHeight,
        ReaderFontSize = settings.ReaderFontSize,
        ReaderWideSpacing = settings.ReaderWideSpacing
    };
}
